name: unit-tests
on:
  [push, pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update the system
        run: |
          sudo apt-get update -y

